### PR TITLE
test: Build with Eask

### PR DESCRIPTION
**Pull request by jcs090218**
Add basic CI test! :)

See the test result in https://github.com/jcs-PR/psysh.el/actions/runs/6168536868?pr=1.

### CODE REVIEW

**Comment by zonuexe** [comment]
@jcs090218 Great, thank you!

**Comment by jcs090218** [comment]
Do you mean to merge this? :)

**Comment by zonuexe** [comment]
@jcs090218 I just forgot to press the button 😄

**Comment by jcs090218** [comment]
No problem at all! 👍 😁

**Pull request merged**
